ZOOLIB_DIR = ../../..
PROJECT_DIR = ${ZOOLIB_DIR}/samples/buttonmessage/buttonmessage_src

ZOOLIB_PATHS := ${ZOOLIB_DIR}/src/_deprecated

include ${PROJECT_DIR}/realmake

include ${ZOOLIB_DIR}/tools/zmake/zmake.engine

