# $Id: makefile,v 1.1 2008/02/29 20:40:13 agreen Exp $

ZOOLIB_DIR ?= ../../../../zoolib
#ZOOLIB_DIR ?= ../../../..

include $(ZOOLIB_DIR)/tools/zmake/zmake.prefix

PROJECT_DIR = ../src

include ${PROJECT_DIR}/realmake

include $(ZOOLIB_DIR)/tools/zmake/zmake.suffix
